In [1]:
import time
import numpy as np

In [2]:
G = np.random.randint(20, size=(100,100))
H = np.random.randint(20, size=(100,100))
a = len(G)
d = int(a/2)
row_factor=np.zeros(a)
column_factor = np.zeros(a)
R = np.zeros((a,a))
my_start_time = time.time()
#Custom multiplication
for i in range(a):
    row_factor[i] = G[i][0] * G[i][1]
    for j in range(1, d):
        row_factor[i] += G[i][2*j - 1] * G[i][2*j]
for i in range(a):
    column_factor[i] = H[0][i] * H[1][i]
    for j in range(1,d):
        column_factor[i] += H[2*j - 1][i] * H[2*j][i]
for i in range(a):
    for j in range(a):
        R[i][j] = -(row_factor[i] + column_factor[j])
        for k in range(d):
            R[i][j] += (G[i][2*k-1]+H[2*k][j])*(G[i][2*k] + H[2*k-1][j])            
if (2 * (a/2)!= a):
    for i in range(a):
        for j in range(a):
            R[i][j] += G[i][b] * H[b][j]
print("--- %s seconds ---" % (time.time() - my_start_time))
dot_start_time = time.time()
#numpy multiplication
RR = np.dot(G,H)
print("--- %s seconds ---" % (time.time() - dot_start_time))

print(G)
print(H)
print(R)

--- 2.0120303630828857 seconds ---
--- 0.0018880367279052734 seconds ---
[[15  1  5 ...  9 16 15]
 [ 5 17 18 ...  4 16  1]
 [17 16 10 ...  2  8  9]
 ...
 [ 2  5 11 ...  2  3 18]
 [14  7  6 ...  4  2 17]
 [ 5 11  8 ... 17  5  0]]
[[ 9 10 16 ...  2 17 11]
 [19  8 13 ...  1  1  0]
 [ 4 18  8 ...  6 17  2]
 ...
 [ 7  8 13 ... 11  7  7]
 [ 9 10 12 ...  6  2 18]
 [ 5 15  7 ...  6 10  8]]
[[7374. 9280. 8681. ... 8732. 8719. 7405.]
 [8209. 9605. 8721. ... 9016. 8504. 7276.]
 [7568. 8555. 8091. ... 7982. 8600. 6818.]
 ...
 [8027. 8750. 8799. ... 9930. 8845. 8226.]
 [8754. 9304. 9624. ... 9506. 9288. 7655.]
 [7927. 8257. 8577. ... 8532. 8221. 7566.]]
